// <auto-generated />
using CollectionOfEntities.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CollectionOfEntities.Persistence.Migrations
{
    [DbContext(typeof(LoanApplicationsDbContext))]
    partial class LoanApplicationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CollectionOfEntities.Model.DecisionHierarchy", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("LoanType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DecisionHierarchies");
                });

            modelBuilder.Entity("CollectionOfEntities.Model.Step", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("DecisionHierarchyId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("OrganizationLevel");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DecisionHierarchyId");

                    b.ToTable("DecisionHierarchySteps");
                });

            modelBuilder.Entity("CollectionOfEntities.Model.Step", b =>
                {
                    b.HasOne("CollectionOfEntities.Model.DecisionHierarchy", null)
                        .WithMany("Steps")
                        .HasForeignKey("DecisionHierarchyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CollectionOfEntities.Model.DecisionHierarchy", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
